export const ImagenesGatos = [
    'gato (1)',
    'gato (2)',
    'gato (3)',
    'gato (4)',
    'gato (5)',
    'gato (6)',
    'gato (7)',
    'gato (8)',
    'gato (9)',
    'gato (10)',
    'gato (11)',
    'gato (12)',
    'gato (13)',
    'gato (14)',
    'gato (15)',
    'gato (16)',
    'gato (17)',
    'gato (18)',
    'gato (19)',
    'gato (20)',
    'gato (21)',
    'gato (22)',
    'gato (23)',
    'gato (24)',
    'gato (25)',
    'gato (26)',
    'gato (27)',
    'gato (28)',
    'gato (29)',
    'gato (30)',
    'gato (31)',
    'gato (32)',
    'gato (33)',
    'gato (34)',
    'gato (35)',
    'gato (36)',
    'gato (37)',
    'gato (38)',
    'gato (39)',
    'gato (40)',
    'gato (41)',
    'gato (42)',
    'gato (43)',
    'gato (44)',
    'gato (45)',
    'gato (46)',
    'gato (47)',
    'gato (48)',
    'gato (49)',
    'gato (50)',
    'gato (51)',
    'gato (52)',
    'gato (53)',
    'gato (54)',
    'gato (55)',
    'gato (56)',
    'gato (57)',
    'gato (58)',
    'gato (59)',
    'gato (60)',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
    // 'gato ()',
] 